### ISSUE TITLE
Integrate parallel QDNAseq

### ISSUE THREAD

**Issue by sambrightman** [hartwigmedical/pipeline#10]
ccagc/QDNAseq#44 will make QDNAseq 10-20x faster but needs to be tested by author and integrated into a release. As described in the PR, parameterisation needs to be cleaned up a bit to pass in the correct number of threads – the default is targeted as single-run usage on a dedicated machine (`num_cores - 2`). We want to wire through `QDNASEQ_THREADS` to `run_QDNAseq.R` and add `MulticoreParam(workers=num_threads)` or similar).

**Comment by kduyvesteyn** [comment]
QNASeq is decommissioned
