### ISSUE TITLE
FreeBayes 1.1+ tasks

### ISSUE THREAD

**Issue by sambrightman** [hartwigmedical/pipeline#11]
- As per UMCUGenetics/IAP#71 we should use `--strict-vcf`.
- FB 1.1 is also supposed to be substantially faster but it was a large change. For me two tests are failing. Needs regression testing.
- Also has multiple minor fixes that affect us for some use-cases e.g. my ekg/freebayes#327

**Comment by kduyvesteyn** [comment]
We are moving away from freebayes
