### ISSUE TITLE
Metadata file

### ISSUE THREAD

**Issue by roelj** [hartwigmedical/pipeline#16]
First of all, thanks for this pipeline.

Could you share a (dummy) example of the `metadata` file needed to describe which sample is the tumor, and which sample is the reference?

Thanks!

**Comment by kduyvesteyn** [comment]
A minimal metadata file would like this.
set_name is the name of the directory you write to.

```
{
    "ref_sample": "CPCT12345678R",
    "tumor_sample": "CPCT12345678T",
    "set_name": "korneel_pipeline_test"
}
```

**Comment by roelj** [comment]
Thanks!  I was missing the `set_name`.  What does it do?

**Comment by kduyvesteyn** [comment]
Its used in the automation we have around the pipeline but I am pretty sure it doesn't do anything inside the pipeline actually. Would be better actually if it were not necessary actually...

**Comment by roelj** [comment]
Okay.  Thanks for the quick and useful responses.
