### ISSUE TITLE
File permissions of scripts not preserved

### ISSUE THREAD

**Issue by roelj** [hartwigmedical/pipeline#18]
It seems that `rcopy` does not preserve file permissions, which causes `StrelkaPostProcess` to fail, because it cannot execute the `annotatePON.py` script.

The relevant line is here:
https://github.com/hartwigmedical/pipeline/blob/master/lib/HMF/Pipeline/Config.pm#L246

We could explicitly add a `chmod` line after the `rcopy` to ensure the execution bits are set.
```
chmod 0555, catfile($opt->{OUTPUT_DIR}, "scripts", "annotatePON.py"), 
            catfile($opt->{OUTPUT_DIR}, "scripts", "convert_delly_TRA.pl")
```

But that hardcodes the script's filenames.

**Comment by Seth-Karlo** [comment]
Hi @roelj , could you give me the output of the following command please?

`perl -MFile::Copy::Recursive -e 'print $File::Copy::Recursive::VERSION'`

Andy

**Comment by roelj** [comment]
Hi @Seth-Karlo, thanks for looking into this.
The output is `0.38`.

**Comment by Seth-Karlo** [comment]
@roelj We don't see the same behaviour at our end. Could you confirm the type of OS you are using, the filesystem being used and your current version of Perl please?

**Comment by roelj** [comment]
@Seth-Karlo, thanks for testing. This is on an NFS-mounted filesystem.  The scripts are copied between two NFS-mounted volumes.

The base OS:
```
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core) 
Release:        7.4.1708
Codename:       Core
```
But we use GNU Guix (at commit `1f6f4c40`), with the pipeline packaged in:
https://github.com/UMCUGenetics/guix-additions/blob/master/umcu/packages/hmf.scm

So the effective Perl version used is:
```
$ perl -v 

This is perl 5, version 26, subversion 0 (v5.26.0) built for x86_64-linux-thread-multi
...
```

Additionally, I can confirm that these scripts are executable at their source location:
```
$ ls -lh /gnu/profiles/per-program/hmf-pipeline/share/hmf-pipeline/scripts/
total 368K
-r-xr-xr-x  13 root root 6.6K Jan  1  1970 annotatePON.py
-r-xr-xr-x  13 root root 1.8K Jan  1  1970 convert_delly_TRA.pl
-r-xr-xr-x 124 root root 3.0K Jan  1  1970 makeBAFplot.R
-r-xr-xr-x 124 root root 2.4K Jan  1  1970 makeKaryotype.R
-r--r--r-- 124 root root 2.0K Jan  1  1970 run_QDNAseq.R
```

**Comment by kduyvesteyn** [comment]
We only test for perl v5.16 till v5.24, see also https://travis-ci.org/hartwigmedical/pipeline
Though I doubt that could cause this issue... will test it.

**Comment by kduyvesteyn** [comment]
Pipeline runs fine on travis on perl 5.26, so must be something more deep at your end @roelj

**Comment by Seth-Karlo** [comment]
Do you run the pipeline with the same user who owns the script? Also, what options have you mounted NFS with?

**Comment by roelj** [comment]
@Seth-Karlo, no, `root` owns the scripts, and my user count (which is not `root`) copies the script.

The mount options:
The scripts are copied from `/gnu` to `/hpc`

For `/gnu`:
```
type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountvers=3,mountport=300,mountproto=udp,local_lock=none
```

For `/hpc`:
```
type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountvers=3,mountport=300,mountproto=udp,local_lock=none)
```

I tried copying a file from a `/gnu` folder to a `/hpc` folder using `cp`:
```
$ ls -lh /gnu/repositories/test.sh 
-rwxr-xr-x 1 rjanssen2 root 0 Nov 14 14:21 /gnu/repositories/test.sh
$ ls -lh | grep test.sh
-rwxr-xr-x  1 rjanssen2 cog           0 Nov 14 14:21 test.sh
```

So, the execution permissions are correct using `cp`.

**Comment by Seth-Karlo** [comment]
@roelj I suspect the issue is that your user is copying from root. Can you try changing the scripts to be owned by yourself please and see if that resolves your issue?

**Comment by roelj** [comment]
I copied the `root`-owned annotatePON.py using `cp`, and here's the result:
```
$ cp /gnu/profiles/per-program/hmf-pipeline/share/hmf-pipeline/scripts/annotatePON.py .
$ ls -lh | grep annotatePON.py 
-r-xr-xr-x  1 rjanssen2 cog        6.6K Nov 14 14:59 annotatePON.py
```

So copying files from root is no different than copying files from the same user (as far as the system is concerned).

There's a difference between the system `cp` and Perl's `rcopy`.

I have one other solution: Prefix the interpreter (`python` and `perl` to the command(s)).

**Comment by roelj** [comment]
I applied the solution of prefixing the interpreter. See https://github.com/UMCUGenetics/guix-additions/commit/a6e98ef261d5f995ddfdd648c45b6ddc97809df3.

Thanks for looking into this.
