### ISSUE TITLE
scripts for identify gene fusions

### ISSUE THREAD

**Issue by LeaveYeah** [hartwigmedical/pipeline#20]
Hi, in the pan-cancer whole genome analysis paper, the structural variants are examined for gene fusions. I would like to know if the related scripts are available. Thank you very much!

**Comment by kduyvesteyn** [comment]
They are created by variant-annotator module in hmftools. 

Do note that the latest version (v2.2) is designed for GRIDSS specifically. If you'd like to run on Manta/BPI you should take v1.6

Another question - out of interest - who are you? Your github user makes it a little hard to figure out!

**Comment by LeaveYeah** [comment]
Keep it between you and me, I am secretly recruited by the Avengers to do a pan-villain whole genome analysis:)

Kidding aside, I am a PhD student from Bioinformatics Algorithm Lab of The University of Hong Kong. I am now on exchange at Mayo Clinic. I am working on a WGS pipeline similar to yours to apply for our own data.

**Comment by LeaveYeah** [comment]
Thank you very much for your answer by the way. Brilliant works!

**Comment by kduyvesteyn** [comment]
We have made quite some improvements to our pipeline since we pre-published the paper, if you are interested in more structured overview please shoot me a mail at k.duyvesteyn-hartwigmedicalfoundation.nl
